# We need some comments here

trigger:
  branches:
    include:
    - '*'
    exclude:
      - refs/tags/*

stages:
- stage: build
  jobs:
  - job: linux
    pool:
      vmImage: 'ubuntu-latest'
  
    steps:  
    - checkout: self
      fetchDepth: 3
  
    - script: |
        sudo apt-get update
        sudo apt-get install gcc
      displayName: Install dependencies

    - script: |
        cd $(Build.SourcesDirectory)/nodesdk
        npm install
      displayName: Initialize
        
    - script: |
        cd $(Build.SourcesDirectory)/nodesdk
        npx node-gyp rebuild
      displayName: Build NAPI C++
        
    - script: |
        cd $(Build.SourcesDirectory)/nodesdk
        npm run tsc
      displayName: Compiling TypeScript
        
    - script: |
        cd $(Build.SourcesDirectory)/nodesdk
        npm run generatemeta
      displayName: Generating meta info for testing

  - job: windows
    pool:
      vmImage: 'windows-latest'
    
    steps:
    - checkout: self
      fetchDepth: 3
    
    - script: |
        cd $(Build.SourcesDirectory)/nodesdk
        npm install
      displayName: Initialize
        
    - script: |
        cd $(Build.SourcesDirectory)/nodesdk
        npx node-gyp rebuild
      displayName: Build NAPI C++
        
    - script: |
        cd $(Build.SourcesDirectory)/nodesdk
        npm run tsc
      displayName: Compiling TypeScript

    - script: |
        cd $(Build.SourcesDirectory)/nodesdk
        npm run generatemeta
      displayName: Generating meta info for testing

  - job: mac
    pool:
      vmImage: 'macos-latest'

    steps:
    - checkout: self
      fetchDepth: 3
    
    - script: |
        cd $(Build.SourcesDirectory)/nodesdk
        npm install
      displayName: Initialize
        
    - script: |
        cd $(Build.SourcesDirectory)/nodesdk
        npx node-gyp rebuild
      displayName: Build NAPI C++
        
    - script: |
        cd $(Build.SourcesDirectory)/nodesdk
        npm run tsc
      displayName: Compiling TypeScript

    - script: |
        cd $(Build.SourcesDirectory)/nodesdk
        npm run generatemeta
      displayName: Generating meta info for testing

  - job: audit
    displayName: Npm-auditing packages
    dependsOn: linux

    steps:
    - script: |
        cd $(Build.SourcesDirectory)/nodesdk
        npm audit
      displayName: Npm audit

  - job: testapp
    displayName: Starting testapp
    dependsOn: linux

    steps:
    - script: |
        cd $(Build.SourcesDirectory)/testapp
        npm install
      displayName: Installing testapp dependencies

    - script: |
        cd $(Build.SourcesDirectory)/testapp
        npm run start
      displayName: Starting testapp
